VOICEVOX/voicevox_blog

- src/pages/index.tsx
ref: https://github.com/Hiroshiba/voicevox_core/issues/23
> 全体構成への言及を追加

- src/components/seo.js
セキュリティ関係の<meta>を追加します。
seo.js に書いてしまったのですが、大丈夫でしょうか。
タグはそれぞれ
Cross Site Scripting (XSS) や data injection 攻撃を防ごうという気持ちを表明します。
HTTP経由で提供されるURL をセキュリティで保護されたHTTPSを介して提供されるものに置き換えられたかのように処理するよう指示します。
セキュリティとは関係ないですが、サーバをFLoCの分析対象から外します。
クリックジャッキング攻撃の対策をします。
セキュリティ的にはあまり意味はないですが、SEO対策には良いと思います。
> セキュリティ関係の<meta>を追加

- src/scripts/linuxInstallNvidia.sh
GPU版linux VOICEVOXをインストールするとき、環境変数にNAMEが定義済みだと挙動がおかしくなるので修正
- https://github.com/VOICEVOX/voicevox/issues/635
> GPU linuxインストール時にNAMEを指定する

- src/markdowns/howToUse.md
いい加減VOICEVOX org内のリポジトリで作業するのをやめて、個人リポジトリで作業できるようにしたいと思いました。
リダイレクトが死んでしまいますが、こんな感じの案内を出そうとと思います。
https://github.com/Hiroshiba/voicevox_engine
> リポジトリのURLをHiroshibaからVOICEVOXに

- src/components/downloadModal.tsx
`downloadUrls`が
```typescript
Record<
OsType,
Record<
ModeType,
Record<
PackageType,
{ url: string; name: string }
>
>
>
```
だったのを
```typescript
Record<
OsType,
Partial<Record<
ModeType,
Partial<Record<
PackageType,
{ url: string; name: string }
>>
>>
>
```
に変更し，型エラーを修正しました．
> `downloadUrls`の型の修正

- src/components/audioSample.tsx
HTMLのイベントに関する知識が足りてませんでした。
スタイル一覧ボタンをクリックしてもスタイルメニューが開かない
→　onFocusがボタンではなかったから（だと思います）
スタイルをクリックしてもスタイルが変わらない
→　onClickはonBlurの後に呼ばれるから
close #93
> スマホでスタイルが変更できない問題の修正

- src/hooks/useDetailedCharacterInfo.ts
- src/pages/dormitory/{Character.characterId}.tsx
- src/types/dormitoryCharacter.tsx
タイトルのとおりです。
そのままのバストアップ画像を適用する形だと、顔の部分がクロップされちゃうのと、画質がいまいちでした。
バストアップ画像の上部分を適用するのがいい感じだったので、こうしてみました。
こんな感じになる予定です！
ref https://ogimage.tsmallfield.com/
ref #79 
すでにデプロイ済みです。
> ボイボ寮生OGP画像を、バストアップ画像のトップ部分に変更

- src/components/dormitoryCharacterModal.tsx
- src/components/layout.scss
- src/hooks/useDetailedCharacterInfo.ts
- src/pages/product/{Character.characterId}.tsx
「縦幅を揃えつつ画像を極力大きく表示し、中央に表示するのを任意の縦横比で行う」というのがGatsbyImageでできなかった･･･。
代わりに立ち絵を全てアスペクト比１にし、表示領域がせいほうけいくらいになるかならないかあたりでobject-fitを切り替えるようにした。
もしどうしてもGatsbyImageがサポートしていない表示形式を実現したいなら、GatsbyImageの全スタイルを消すところから始めたほうが良さそう。
（かなり特殊なことをしていました。）
なにもしないimgを召喚できるようなラッパーを書いても良いかもしれない。
> 製品ページでの画像見切れが起きにくくする

- src/components/dormitoryCharacterCard.tsx
- src/components/layout.scss
- src/pages/dormitory.tsx
以下を実施しました。
- キャラクター画像が途切れてる感じをなくす
- 画像の上にpaddingを追加
- 画像と名前の間にも罫線を追加
- キャラクターカードの縦の見かけ上のpaddingを横に合わせる
- 7期生の上にも水平線(hr)を追加
- 水平線の位置を微調整
PC変更前
PC変更後
モバイル変更前
モバイル変更後
`display: grid`で書きなおした方が良さそうにも見えますが、とりあえず現状に合わせました。
> ボイボ寮のキャラクター一覧の見た目を改善

- src/components/layout.scss
- src/pages/dormitory.tsx
- src/pages/dormitory/call_names.tsx
- src/pages/dormitory/call_names/index.tsx
ボイボ寮キャラクターの呼称表 (呼び方一覧表) のコピー機能を実装します.  
また, #163 に関連して以下のような修正を行います:  
~~- URL アンカー (`#{characterId}`) で飛んだときに画面の中心にスクロールするように~~
~~- ﾁｮｯﾄハイライトアニメーション付けました (discord/slack みたいな)~~
- ボイボ寮にある呼称表へ飛ばすリンクが `call-names` になったまま (#167 のミス？) なので `call_names` に
- セルにホバーしたら, “クリックしてコピー: 「ずんだもん」” のように出てくるようにしてみました
refs:  
- #163 
- #167 
_準備中_
不要な機能があれば遠慮なくお教えください！！！
> Add: ボイボ寮キャラクターの呼称のコピー機能 + リファクタリング

- src/components/downloadModal.tsx
- src/components/softwareFeature.tsx
トップページのダウンロードボタンの下部に利用規約ページに遷移するボタンを追加
close #181
> ダウンロードボタンの近くに利用規約ボタンを追加

- src/components/layout.scss
- src/components/ossGuidance.tsx
- src/components/page-footer.tsx
- src/pages/index.tsx
- src/pages/song/index.tsx
- OSSへの案内部分をコンポーネントへ
- ソングページ下部にOSSへの案内を追加
- ソングページのハミングの説明の幅を調整
close #204
> OSSに関する案内をソングページに追加

- README.md
- package.json
- src/updateVersion.ts
エディタのバージョン更新を一部忘れてしまっていたので、間違いないようにバージョン更新用のコードを書いてみました。
複数の箇所のバージョンを書き換える必要があるのですが、それを一括で行ってくれるようになっています。
tsxで実行しています。
- https://github.com/VOICEVOX/voicevox_blog/pull/225
本当はそもそも1箇所変えてビルドすればいい感じになるようにすべきだけど、一旦これで。。。
> add: バージョン更新用のコードを設置

- src/components/layout.scss
- src/pages/dormitory/{Character.characterId}.tsx
> Add: ボイボ寮側のキャラページの呼び方に不明時の表示を追加

- src/components/downloadModal.tsx
#231 を修正します。
- closes: #231
（なし）
Windows -> CPU -> Linuxみたいな順にクリックしたときの挙動がホンの少し変わりますがまぁそんなことをする人はめったにいないので大丈夫かと
> Fix: ダウンロードダイアログのOS変更時の挙動を修正、OSによって初期選択が変わるように

- README.md
- public/nemoLatestDefaultEngineInfos.json
- src/tools/generateLatestDefaultEngineInfos.ts
エディタ側のテストに必要になったので作ってみました。
（特にデフォルトエンジンとしてNemoを搭載する予定はありません。）
- https://github.com/VOICEVOX/voicevox/pull/2444
`latest default engine info`という名前にしてるけど、普通に`latest engine info`という名前でもいいかも･･･？
デフォルトエンジンを前提とすべきか否か･･･。
> add: Nemo用のデフォルトエンジンの更新情報を追加

- src/layouts/Base.astro
GA4がしばらく動いてない状態になってしまっていたので直します。
argmentsを渡さないとgoogle analyticsがちゃんと動いてくれないらしいことに気づいてませんでした･･･。
GA4のデバッグ方法のメモ。
Google Analytics内の`DebugView`に表示されるものがたぶん正義。
`debug_mode: true`をconfigで指定すればOK。
Google Analytics内に`debug_mode: true`のフィルタがあるので有効にしておく。
これを使っててもDebugViewには表示されるはず。
`astro:page-load`でconfigを設定した場合、SPA的な遷移はpage viewにカウントされない。
自分で`page_view`イベントを送る。
`/collect`にnetwork送信が発生しているかどうかでデバッグできる。
開発ツールのnetworkで`collect`でフィルタするとわかりやすい。
Astroの`define:vars`とかも普通に使える。
partytownも再度試したけどなんか動かなかった。`window.gtag`をforwardすれば良さそうな気配は感じる。
> fix: Google Analyticsのバグを修正

- src/layouts/Base.astro
debug_mode: falseを指定してもデバッグモードが解けない。
キーをなくすのが正解らしい。
> fix: デバッグモードのオプション設定方法を正しくする

- README.md
- public/latestDefaultEngineInfos.json
- public/nemoLatestDefaultEngineInfos.json
- src/components/modal/download/DownloadNemoModal.tsx
- src/constants/index.ts
- src/tools/generateLatestDefaultEngineInfos.ts
Nemoのバージョンも0.23.0に上げて、arm64版vvppをダウンロード可能にします。
> build: Nemoのバージョンを0.23.0に

- src/pages/product/[characterId].astro
- tests/e2e/ui/product.spec.ts
↓２つのコメントの実装です。
- https://github.com/VOICEVOX/voicevox_blog/pull/267#pullrequestreview-2747336778
- https://github.com/VOICEVOX/voicevox_blog/pull/267#pullrequestreview-2747617380
リストからキャラクターを選んだとき、即座にそのキャラクターのアイコンが中央に移動するようにします。
結局`<script is:inline>`にしました。。。
ドキュメントのここ↓によると、is:inlineに書いたのは２回以上実行されうるというのと、
（まあこれは単一コンポーネントだから関係ないかも）
https://docs.astro.build/en/guides/client-side-scripts/#opting-out-of-processing
あと実行タイミングがそのスクリプトが読み込まれた時点になるので若干不安定だということもあり、`is:inline`を付けないほうが良いかなぁと思ってました。
（とはいえ実行されるのは必ずDOMが読み込まれたあと･･･なはず）
`<script>`にしたところ、実行されるタイミングが思ってるよりだいぶ遅いことがわかりました 😇 
ちなみに今のastroのバージョンだと、`pnpm start`でやってるときと`pnpm build && pnpm preview`したときだと`<script>`が実行されるタイミングがだいぶ違います。
`preview`時のが圧倒的に速い･･･のですが、それでもwebを低速モードにするとタイミングが微妙でした。。
（画像が読み込まれてから実行される） …
> feat!: 製品ページで選んだキャラクターが即座に中央に表示するようにし、テストも追加

- eslint.config.mjs
- package.json
- pnpm-lock.yaml
- src/helper/index.ts
- src/helper/playwrightHelper.ts
- src/tools/generateThumb.mts
- tests/e2e/helper.ts
- tests/e2e/meta/index.spec.ts
- tests/e2e/screenshot/helper.ts
- tests/e2e/ui/nemo.spec.ts
- tests/e2e/ui/product.spec.ts
- tests/e2e/ui/song.spec.ts
- tests/e2e/ui/talk.spec.ts
テストがわかりやすいようにstepで区切るようにしました。
これでe2eテストを実行して落ちた時も分かりやすいし、実際に作る時もどこまで進んだかが日本語で表示されるので分かりやすいはず。
> refactor(test): テストがわかりやすいようにstepで区切るように
