VOICEVOX/voicevox_blog

README.md, src/components/downloadModal.tsx, src/pages/dormitory.tsx, src/pages/index.tsx, src/scripts/linuxInstallCpu.sh, src/scripts/linuxInstallNvidia.sh
org化に伴ってURLが変わったので修正しました
close https://github.com/VOICEVOX/voicevox_blog/issues/7
=> Hiroshiba to VOICEVOX

src/components/modalPrivacyPolicy.tsx, src/markdowns/privacyPolicy.md, src/pages/index.tsx
google analyticsのプライバシーポリシーを追記
=> プライバシーポリシーを追加

gatsby-browser.js, src/components/layout.scss
autoAddCssによるcssロードを無効にして、フォントの表示が一瞬崩れる不具合を修正する。
ref #5
=> fontawesomeの表示がちらつく不具合を修正

src/components/page.tsx, src/pages/dormitory.tsx, src/pages/index.tsx
共通Pageコンポーネントを作成して、とりあえずfotterだけ移動してみました。
ref: https://github.com/VOICEVOX/voicevox_blog/issues/18
=> 共通Pageコンポーネントを作成

src/components/layout.scss
Appple系で起こるらしいフォントレンダリングの問題を解決します。
ref https://github.com/VOICEVOX/voicevox_blog/pull/24
=> フォントのアンチエイリアスを変更

src/components/downloadModal.tsx, src/pages/dormitory.tsx, src/pages/index.tsx, src/scripts/linuxInstallCpu.sh, src/scripts/linuxInstallNvidia.sh
=> バージョン0.9.4、雨晴はう追加

src/components/downloadModal.tsx
=> linuxのGPU版のzipのリンクが間違っていたので修正 #41

src/pages/index.tsx
=> mac対応の文言追加

src/pages/index.tsx
=> releasedにする

src/markdowns/qAndA.md
=> サポートOSを追記（ VOICEVOX/voicevox#715 ）

src/components/page.tsx
=> ヘッダーにハンバーガーボタンを表示

src/components/downloadModal.tsx
=> nvidia以外のGPUにも対応したので文言変更

README.md
=> READMEにプレビュー環境に関する記述を追加

src/components/layout.scss, src/components/page.tsx, src/pages/dormitory.tsx, src/pages/index.tsx
@k-chop 長年の悩みが解決しました！！！ありがとうございます！！！！！
close #125
=> ヘッダーを点滅しないようにした

.env.development, .env.preview, .env.production, README.md, gatsby-config.js, package-lock.json, package.json
プレビューページでもOGPの画像のURLが正しくなったりします
=> previewのときはBASE_URLを変更

.env.development, .env.preview, .env.production, gatsby-config.js, package-lock.json, package.json
URLはDEPLOY_URLで取れるらしい
https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata
=> netliftでうまく動かなかったのでDEPLOY_URLに

.env.development, .env.production, gatsby-config.js
DEPLOY_URLが.envに上書きされてしまうので修正･･･。
=> NETLIFYフラグを見てURLを判断するように変更

src/components/dormitoryTopIllustContainer.tsx, src/pages/dormitory.tsx
本日2023年4月5日(水)の朝か昼ごろにリリース予定です。
=> ６期生トップイラスト追加・差し替え

src/hooks/useDetailedCharacterInfo.ts
=> 九州そらの説明が間違っていたので修正

src/components/layout.scss, src/pages/product/{Character.characterId}.tsx
キャラクターページの上下が切れることがあるのを修正しました。
=> キャラクターページの上下が切れることがあるのを修正

src/components/layout.scss, src/pages/dormitory.tsx, src/pages/dormitory/call-names/index.tsx
* デザイン的に色々調整
* ページレイアウトを変えたり
* bulmaの気持ちに合わせる
#163 
二重スクロールをなくしたい点などをFIXMEコメントにして追加しています 🙇
=> キャラクター呼称表ページ周りのデザイン等の調整

README.md, src/constants.ts, src/data/updateInfos.json, src/markdowns/howToUse.md, src/pages/index.tsx, src/scripts/linuxInstallCpu.sh, src/scripts/linuxInstallNvidia.sh
=> to 0.14.10

src/components/dormitoryTopIllustsContainer.tsx, src/pages/dormitory.tsx
=> ボイボ寮トップイラストを８枚目に更新

src/scripts/linuxInstallCpu.sh, src/scripts/linuxInstallNvidia.sh
=> fix: linuxの0.19.0化を忘れていた

src/components/nemoDownloadModal.tsx, src/constants.ts
Nemo 0.20.0をダウンロードできるようにします。
- https://github.com/VOICEVOX/voicevox_project/discussions/54
=> Nemo 0.20.0

README.md, package-lock.json, package.json, src/data/latestDefaultEngineInfos.json, src/generateLatestDefaultEngineInfos.ts
VOICEVOXデフォルトエンジンのVVPPのURLの場所を記載したjsonを作成するコードと、そのjsonファイルを作りました。
エディタ側の[エンジンを切り離すタスク](https://github.com/VOICEVOX/voicevox/issues/1194)用です。
- https://github.com/VOICEVOX/voicevox/issues/1194
- https://github.com/VOICEVOX/voicevox_engine/pull/1464
ファイルフォーマットは不足があれば変わるかも。
リリース後はもちろん変わらない予定。
=> VOICEVOXデフォルトエンジンの更新情報を作成

src/constants.ts
Nemoのバージョンを更新します。
- https://github.com/VOICEVOX/voicevox_project/discussions/55
=> nemo to 0.21.0

src/scripts/linuxInstallCpu.sh, src/scripts/linuxInstallNvidia.sh
0.20に取り残されていたので修正します。
- closes: voicevox/voicevox#2310
（なし）
CI作っても良いかも？
=> Fix: Linux版インストーラーのバージョンの不一致を修正

src/layouts/Base.astro
ダークモードだと一部が勝手にダークモード化するので、強制的にライトモードを適用するようにしました。
Discordでたくしぃさんに教わって気づきました、ありがとうございます！
https://discordapp.com/channels/879570910208733277/893889888208977960/1320826081686716497
=> fix: 常にライトモードを適用するように

src/data/updateInfos.json
- https://github.com/VOICEVOX/voicevox_blog/pull/240
で`更新情報ファイルをコピーすることにしました`と書いていますが、実際にコピーするのを忘れていました･･･。
適当に0.24か0.25くらいまでコピーし続けようと思います。
=> add: src/data/updateInfos.jsonコピー忘れ

src/components/Footer.astro, src/components/Header/Header.tsx, src/layouts/Base.astro, src/styles/fonts.scss
lighthouseの結果をちょっと反映します。
あまり変えられなかった。
=> chore: lighthouseの結果をちょっと反映

src/pages/product/[characterId].astro
以前は実装していたアニメーションをいつか復活しようかなと思って残していたんですが、まあ普通に邪魔になっているので削除したいと思います！
もし実装し直す時はこのプルリクエストを参考にすると、どういうコードにすればいいかわかるかも。
=> refactor(ui): 製品ページ内の不要なコメントアウトコードを削除

.github/workflows/DANGEROUS_trigger_preview_pages.yml, .github/workflows/build_preview_pages.yml
PRの内容をプレビューするようにします。
- ref: https://github.com/VOICEVOX/preview-pages/pull/35
（なし）
（なし）
=> feat: PRプレビューを追加

.github/workflows/DANGEROUS_trigger_preview_pages.yml, src/components/Header/Header.tsx, src/components/modal/download/DownloadModal.tsx, src/components/modal/download/DownloadNemoModal.tsx, src/helper/index.ts, src/pages/_LinkListSection.astro, src/pages/_OssGuidanceSection.astro, src/pages/dormitory/[characterId]/[...descriptionType].astro, src/pages/dormitory/[characterId]/_CallBox.astro, src/pages/dormitory/[characterId]/_TypeButton.astro, src/pages/dormitory/_ExplainSection.astro, src/pages/dormitory/_TopIllustsContainer.astro, src/pages/dormitory/call_names/index.astro, src/pages/dormitory/index.astro, src/pages/index.astro, src/pages/news/index.astro, src/pages/product/_TopContainer.astro, src/pages/song/CharacterCard.tsx, src/pages/song/index.astro, src/pages/talk/_CharacterCard.astro
baseUrlがなくてaが軒並み壊れてたので修正します。
（なし）
（なし）
（なし）
=> fix: baseUrlをつける

src/pages/dormitory/_CharacterCard.astro
- https://github.com/VOICEVOX/voicevox_blog/pull/278
の追加PRです！
つけ忘れを検知するようなテストがあると良さそうだけど、方法が思いつかない･･･。
=> fix: withBaseUrlを使用してリンク忘れを追加

.github/workflows/build_preview_pages.yml
=> fix: build_preview_pages.ymlがmasterへのpushで起動していなかったのを修正
